module.exports = [
  "accelerate the growth of",
  "accept",
  "acquire",
  "activate",
  "adapt with",
  "add",
  "adhere to",
  "adjust",
  "administer medicine to",
  "administrate",
  "admire",
  "advance",
  "advise",
  "advocate against",
  "advocate for",
  "agree with",
  "aid",
  "alter",
  "amuse",
  "analyse",
  "annoy",
  "anticipate",
  "approach",
  "are chosen by",
  "are damaged by",
  "are deceived by",
  "are delivered to",
  "are destroyed by",
  "are documented by",
  "are earned by",
  "are edited by",
  "are eliminated by",
  "are employed by",
  "are enlarged by",
  "are enriched by",
  "are entertained by",
  "are expanded by",
  "are freed by",
  "are killed by",
  "are lectured by",
  "are measured by",
  "are modified by",
  "are multiplied by",
  "are nailed by",
  "are noticed by",
  "are nuked by",
  "are obeyed by",
  "are operated on by",
  "are processed by",
  "are produced by",
  "are ranked by",
  "are recycled by",
  "are reduced by",
  "are taught Chinese by",
  "are taught English by",
  "are taught manners by",
  "are taught maths by",
  "are taught philosophy by",
  "are taught physical fitness by",
  "are taught psychology by",
  "are taught religions by",
  "are taught science by",
  "are taught street smarts by",
  "are transformed into",
  "argue with",
  "arrange",
  "arrest",
  "ask for forgiveness from",
  "ask for help from",
  "ask impossible favors of",
  "ask stupid questions to",
  "assemble",
  "assist",
  "attack",
  "attack",
  "attain",
  "attract",
  "augment",
  "automate",
  "avoid",
  "balance",
  "bang",
  "bargain with",
  "battle",
  "beg for forgiveness from",
  "borrow things from",
  "build",
  "bury things with",
  "bury",
  "buy things from",
  "buy",
  "buy",
  "calculate numbers with",
  "calculate risks with",
  "capitalize on",
  "capture",
  "carry out nefarious plans with",
  "carry",
  "cast shadows on",
  "catalogue",
  "challenge",
  "chase",
  "choke",
  "choose",
  "claim",
  "clean",
  "clear levels of",
  "collaborate with",
  "collect",
  "collect",
  "combine",
  "communicate with",
  "complete",
  "compute",
  "conceive",
  "conceptualize",
  "condense",
  "confuse",
  "consolidate power with",
  "construct",
  "consume",
  "control",
  "convert",
  "coordinate",
  "correct",
  "count",
  "create life with",
  "create",
  "crush",
  "cultivate",
  "cut",
  "damage",
  "deceive",
  "decrease the number of",
  "delight",
  "deliver",
  "deliver",
  "describe",
  "design",
  "destroy",
  "develop",
  "die from",
  "direct groups of",
  "discover secrets about",
  "discover",
  "dispatch",
  "distribute",
  "document",
  "download",
  "earn",
  "eat",
  "edit",
  "eliminate",
  "employ",
  "encourage",
  "endorse",
  "enforce",
  "engage with",
  "engineer",
  "enlarge",
  "enrich",
  "entertain",
  "erase",
  "escuse",
  "establish bases with",
  "estimate the amount of",
  "examine",
  "expand",
  "explain",
  "explore",
  "facilitate",
  "fall on",
  "familiarize",
  "fashion",
  "fight",
  "find",
  "fit together",
  "fix",
  "fly",
  "focus on",
  "follow",
  "follow",
  "form groups of",
  "formalize",
  "formulate",
  "fortify",
  "frame",
  "fulfil",
  "furnish rooms with",
  "gain",
  "gather",
  "generate",
  "govern cities of",
  "grab",
  "group together",
  "guide",
  "handle",
  "harass",
  "hire",
  "host",
  "hunt",
  "hurt",
  "identify",
  "illuminate",
  "illustrate",
  "implement",
  "improve",
  "improvise",
  "increase the amount of",
  "indoctrinate",
  "influence",
  "innovate",
  "inquire about",
  "inspect",
  "inspect",
  "inspire",
  "install",
  "instruct",
  "insult",
  "interrogate",
  "interview",
  "introduce",
  "invent",
  "invest in",
  "investigate",
  "irritate",
  "isolate",
  "jackknife",
  "join",
  "joke with",
  "judge",
  "juggle",
  "jump over",
  "jump over",
  "kick",
  "kill",
  "kiss",
  "knock out",
  "laugh about",
  "laught at",
  "launch",
  "lead",
  "lecture",
  "lick",
  "localize",
  "locate",
  "look at",
  "lose",
  "maintain",
  "manage",
  "map",
  "massacre",
  "maximize",
  "measure",
  "mine",
  "minimize",
  "mock",
  "model",
  "modernize",
  "modify",
  "monitor",
  "motivate",
  "move",
  "move",
  "multiply",
  "nail",
  "negate",
  "notice",
  "nuke",
  "nullify",
  "obey",
  "observe",
  "obtain",
  "obtain",
  "offer",
  "open up",
  "operate on",
  "operate",
  "oppress",
  "order",
  "organize",
  "organize",
  "orientate",
  "overhaul",
  "own",
  "participate with",
  "perceive",
  "perform",
  "prepare for",
  "prevent",
  "prioritize",
  "process",
  "produce",
  "program",
  "promote",
  "propose to",
  "provide for",
  "publicize",
  "purchase",
  "question",
  "quote",
  "raise",
  "rank",
  "rate",
  "react to",
  "record",
  "recycle",
  "reduce",
  "refine",
  "regulate",
  "rehabilitate",
  "reinforce",
  "reject",
  "relate with",
  "remodel",
  "reorganize",
  "repair",
  "research",
  "retrieve",
  "reverse",
  "review",
  "reward",
  "run away from",
  "run with",
  "salvage",
  "score",
  "secure",
  "select",
  "sell",
  "sell",
  "separate",
  "serve",
  "shake",
  "shank",
  "shape",
  "shrink",
  "simplify",
  "slaughter",
  "smash",
  "sneak up on",
  "solve puzzles made out of",
  "somersault",
  "spy on",
  "squeeze",
  "stimulate",
  "strategize with",
  "strengthen",
  "struggle against",
  "study",
  "submit",
  "supervise",
  "supply",
  "support",
  "survey",
  "tailor outfits for",
  "target",
  "teach Chinese to",
  "teach English to",
  "teach manners to",
  "teach maths to",
  "teach philosophy to",
  "teach physical fitness to",
  "teach psychology to",
  "teach religions to",
  "teach science to",
  "teach street smarts to",
  "terminate",
  "test",
  "tighten",
  "trade with",
  "train",
  "transform",
  "translate",
  "transport",
  "treat",
  "tumble over",
  "turn",
  "twist",
  "uncover",
  "unify",
  "upgrade",
  "upload",
  "use",
  "utilize",
  "validate",
  "value",
  "vandalize",
  "verify",
  "view",
  "visit",
  "vomit on",
  "wage war on",
  "walk on",
  "warm up",
  "weigh",
  "welcome",
  "whisper at",
  "win",
  "wish for",
  "wreck",
  "wrestle",
  "wrestle",
  "write about",
  "yawn at",
  "yell at",
  "zap",
  "zoom in on",
];