module.exports = [
  "aid",
  "are crushed by",
  "are forced to battle against",
  "are forced to battle for",
  "are forced to battle with",
  "are forced to believe in",
  "are forced to crush",
  "are forced to destroy",
  "are forced to dismantle",
  "are forced to fight against",
  "are forced to fight for",
  "are forced to help",
  "are forced to join",
  "are forced to live with",
  "are helped by",
  "are in love with",
  "are obliterated by",
  "are overwhelmed by",
  "are overwhelmed with",
  "are spyed on by",
  "are tormeted by",
  "are tortured by",
  "are tortured for",
  "battle against",
  "battle for",
  "battle with",
  "believe in",
  "build up",
  "campaign against",
  "campaign for",
  "can never escape",
  "continue living with",
  "continue",
  "crush",
  "destroy",
  "dismantle",
  "eliminate",
  "empower",
  "enrich",
  "escape",
  "establish",
  "fight against",
  "fight for",
  "gather protesters against",
  "gather resources for",
  "go to war with",
  "help",
  "hide from",
  "impose",
  "introduce",
  "join forces with",
  "live with",
  "love",
  "must be alone with",
  "must escape",
  "must help",
  "must hide from",
  "must obliterate",
  "must oppose",
  "must overcome",
  "must preserve",
  "must repair",
  "receive aid from",
  "run from",
  "set up",
  "sing the praises of",
  "spread the influence of",
  "spy for",
  "spy on",
  "struggle against",
  "struggle with",
  "tear down",
  "try to escape",
  "try to preserve",
  "wage war for",
  "wage war on",
  "win",
];