module.exports = [
  ", and everyone's totally fine with that.",
  ", and it really makes you think.",
  ", and it's horrible.",
  ", and it's kind of gross.",
  ", and it's ridiculously addicting!",
  ", and it's the best thing ever.",
  ", and it's the most important thing you'll ever do.",
  ", and it's totally awesome!",
  ", and it's totally awesome!",
  ", and nobody really likes it that much.",
  ", and nothing happens until you make it happen.",
  ", and pretty much everyone's into it.",
  ", and the music is amazing.",
  ", and there are lots of cars.",
  ", and there are lots of castles.",
  ", and there are lots of dungeons.",
  ", and there are lots of space ships.",
  ", and there are lots of warriors.",
  ", and there's a big focus on resource management.",
  ", and there's local multiplayer.",
  ", and there's lots of world building.",
  ", and there's no way to finish the game.",
  ", and there's too much that you're able to do.",
  ", and you can do pretty much whatever you want.",
  ", and you can't help but watch.",
  ", and you can't let anyone find out!",
  ", and you have to stop them.",
  ", and you have unlimited freedom.",
  ", and you never want to stop playing!",
  ", and, wait for it... aliens!",
  ", and, wait for it... capitalism!",
  ", and, wait for it... communism!",
  ", and, wait for it... confusion!",
  ", and, wait for it... dictatorship!",
  ", and, wait for it... robots!",
  ", and, wait for it... Zerg rush!",
  ", and, wait for it... zombies!",
  "--at night.",
  ". Beautiful.",
  ", because there's nothing wrong with that, right?",
  ", but everything is on fire.",
  ", but everything is underwater.",
  ", but it has a really convoluted story.",
  ", but it's all a big secret.",
  ", but it's all a dream.",
  ", but it's all in your head.",
  ", but it's hard to see anything.",
  ", but it's pitch black.",
  ", but it's really awkward.",
  ", but it's riddled with bugs.",
  ", but some otherworldly force hinders every attempt.",
  ", but the controls are really hard to get the hang of.",
  ", but the story is its main focus.",
  ", but there are limited supplies.",
  ", but there's not really that much to do.",
  "--competitively.",
  "--forever.",
  " in a giant sandbox world.",
  " in an epic struggle against fate.",
  " in broad daylight.",
  " in order to accomplish some evil goal.",
  " in order to accomplish some greater goal.",
  " in order to fulfill a prophesy.",
  " in order to fulfill some holy prophesy.",
  " in public.",
  " in spite of onlookers' disgust.",
  ", in spite of what anyone may say.",
  " in the middle of the night.",
  "--in your dreams.",
  "--in your imagination.",
  "--indefinitely.",
  ", no matter what anyone thinks.",
  ". The controls are super simple.",
  ". The goal is get the lowest score.",
  ". The goal is to achieve world peace.",
  ". The goal is to do it the fastest.",
  ". The goal is to get the highest score.",
  ". The goal is to make everyone feel included.",
  ". The goal is to make everyone feel loved and cared about.",
  ". The goal is to match things.",
  ". The goal is to not be noticed.",
  ". The goal is to not die.",
  ". The real inspiration for the game is a rabbit.",
  ". The real inspiration for the game is coffee.",
  ". The real inspiration for the game is feudal Japan.",
  ". The real inspiration for the game is natural disasters in general.",
  ". The real inspiration for the game is The Sims.",
  ". The real inspiration for the game is the United States.",
  ". There's a blind person in there somewhere, too.",
  ". This game is 100% accessible.",
  " to the chagrin of everyone around.",
  " to try to make everyone happy.",
  " to try to make everyone think.",
  " until everyone dies.",
  " until the end of the world.",
  " until you reach a level cap.",
  " until you run out of supplies.",
  ", with a heavy focus on tight gameplay.",
  "--with meta-game mechanics.",
  "--with multiplayer.",
];