module.exports = [
  "abstract",
  "action role-playing",
  "action-adventure",
  "action",
  "adventure",
  "arcade",
  "art",
  "artsy",
  "atmospheric",
  "ball and paddle",
  "beat-em-up",
  "board",
  "brawler",
  "bullet hell",
  "castle defense",
  "casual",
  "collect-a-thon",
  "cyberpunk",
  "dungeon crawler",
  "dungeoneering",
  "educational",
  "experimental",
  "exploration",
  "falling block",
  "fantasy",
  "farming",
  "fighting",
  "flight simulation",
  "genre-bending",
  "god",
  "hack and slash",
  "historical",
  "horror",
  "illusion",
  "incremental",
  "layered",
  "life simulator",
  "linear",
  "management",
  "maze",
  "medieval",
  "mini",
  "multi-leveled",
  "music",
  "noir",
  "non-linear",
  "one-button",
  "open world",
  "parkour",
  "party",
  "pinball",
  "platform",
  "point and click",
  "puzzle",
  "racing",
  "rail shooter",
  "real-time strategy",
  "roguelike",
  "role-playing",
  "runner",
  "sandbox",
  "sci-fi",
  "shoot-em-up",
  "shooter",
  "simulation",
  "single-screen",
  "space",
  "sports",
  "stealth",
  "story-based",
  "stylized",
  "survival",
  "tactical shooter",
  "tactics",
  "text-based",
  "tower defense",
  "trivia",
  "turn-based strategy",
  "twin stick",
  "tycoon",
  "unconventional",
];