module.exports = [
  ["aardvark", "aardvarks", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["aborigine", "aborigines", {"tone": 4, "type": "person"}],
  ["accessory", "accessories", {"tone": 5, "type": "clothing", "subtype": "jewelry"}],
  ["accident", "accidents", {"tone": 4, "type": "event", "subtype": "action"}],
  ["accomplice", "accomplices", {"tone": 4, "type": "person"}],
  ["accomplishment", "accomplishments", {"tone": 7, "type": "event", "subtype": "action"}],
  ["accountant", "accountants", {"tone": 5, "type": "person"}],
  ["actor", "actors", {"tone": 5, "type": "person"}],
  ["actress", "actresses", {"tone": 5, "type": "person"}],
  ["addressee", "addressees", {"tone": 5, "type": "person"}],
  ["aficionado", "aficionados", {"tone": 6, "type": "person"}],
  ["agency", "agencies", {"tone": 5, "type": "entity"}],
  ["agent", "agents", {"tone": 5, "type": "person"}],
  ["aide", "aides", {"tone": 5, "type": "person"}],
  ["ailment", "ailments", {"tone": 2, "type": "event", "subtype": "internal"}],
  ["airplane", "airplanes", {"tone": 5, "type": "vehicle", "subtype": "air"}],
  ["albatross", "albatrosses", {"tone": 5, "type": "animal", "subtype": "bird"}],
  ["alchemist", "alchemists", {"tone": 5, "type": "person"}],
  ["alien", "aliens", {"tone": 4, "type": "person"}],
  ["alligator", "alligators", {"tone": 5, "type": "animal", "subtype": "reptile"}],
  ["ambassador", "ambassadors", {"tone": 5, "type": "person"}],
  ["amphibian", "amphibians", {"tone": 5, "type": "creature", "subtype": "animal"}],
  ["anaconda", "anacondas", {"tone": 5, "type": "animal", "subtype": "reptile"}],
  ["anchovy", "anchovies", {"tone": 5, "type": "animal", "subtype": "fish"}],
  ["angel", "angels", {"tone": 7, "type": "creature", "subtype": "holy"}],
  ["animal", "animals", {"tone": 5, "type": "creature", "subtype": "animal"}],
  ["answer", "answers", {"tone": 5, "type": "event", "subtype": "action"}],
  ["ant", "ants", {"tone": 5, "type": "animal", "subtype": "insect"}],
  ["anteater", "anteaters", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["antelope", "antelopes", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["antibiotic", "antibiotics", {"tone": 5, "type": "object", "subtype": "drug"}],
  ["antibody", "antibody", {"tone": 5, "type": "component", "subtype": "biological"}],
  ["apartment", "apartments", {"tone": 5, "type": "structure", "subtype": "building"}],
  ["apple", "apples", {"tone": 5, "type": "consumable", "subtype": "fruit"}],
  ["apricot", "apricots", {"tone": 5, "type": "consumable", "subtype": "fruit"}],
  ["archer", "archers", {"tone": 5, "type": "person"}],
  ["ark", "arks", {"tone": 5, "type": "vehicle", "subtype": "water"}],
  ["armadillo", "armadillos", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["aroma", "aromas", {"tone": 7, "type": "event", "subtype": "external"}],
  ["artichoke", "artichokes", {"tone": 5, "type": "consumable", "subtype": "vegetable"}],
  ["article", "articles", {"tone": 5, "type": "object", "subtype": "writing"}],
  ["artisan", "artisans", {"tone": 5, "type": "person"}],
  ["artist", "artists", {"tone": 5, "type": "person"}],
  ["assassin", "assassins", {"tone": 5, "type": "person"}],
  ["asteroid", "asteroids", {"tone": 5, "type": "object", "subtype": "sellar"}],
  ["astronauts", "astronauts", {"tone": 5, "type": "person"}],
  ["athlete", "athletes", {"tone": 5, "type": "person"}],
  ["atom", "atoms", {"tone": 5, "type": "component", "subtype": "elementary"}],
  ["attourney", "attourneys", {"tone": 5, "type": "person"}],
  ["axolotl", "axolotls", {"tone": 5, "type": "animal", "subtype": "amphibian"}],
  ["baby", "babies", {"tone": 5, "type": "person"}],
  ["bachelor", "bachelors", {"tone": 5, "type": "person"}],
  ["backbone", "backbones", {"tone": 5, "type": "component", "subtype": "biological"}],
  ["badge", "badges", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["bag", "bags", {"tone": 5, "type": "object", "subtype": "container"}],
  ["bagpipe", "bagpipes", {"tone": 5, "type": "object", "subtype": "instrument"}],
  ["bailiff", "bailiffs", {"tone": 5, "type": "person"}],
  ["baker", "bakers", {"tone": 5, "type": "person"}],
  ["ball", "balls", {"tone": 5, "type": "object", "subtype": "toy"}],
  ["ballerina", "ballerinas", {"tone": 5, "type": "person"}],
  ["banana", "bananas", {"tone": 5, "type": "consumable", "subtype": "fruit"}],
  ["bandit", "bandits", {"tone": 3, "type": "person"}],
  ["bank", "banks", {"tone": 5, "type": "entity"}],
  ["banker", "bankers", {"tone": 5, "type": "person"}],
  ["banshee", "banshees", {"tone": 3, "type": "creature", "subtype": "monster"}],
  ["barbarian", "barbarians", {"tone": 4, "type": "person"}],
  ["barber", "barbers", {"tone": 5, "type": "person"}],
  ["bard", "bards", {"tone": 5, "type": "person"}],
  ["baron", "barons", {"tone": 5, "type": "person"}],
  ["baseball player", "baseball players", {"tone": 5, "type": "person"}],
  ["baseball", "baseballs", {"tone": 5, "type": "object", "subtype": "toy"}],
  ["basilisk", "basilisks", {"tone": 5, "type": "creature", "subtype": "monster"}],
  ["basket", "baskets", {"tone": 5, "type": "object", "subtype": "container"}],
  ["basketball player", "basketball players", {"tone": 5, "type": "person"}],
  ["basketball", "basketballs", {"tone": 5, "type": "object", "subtype": "toy"}],
  ["bastard", "bastards", {"tone": 2, "type": "person"}],
  ["bat", "bats", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["battalion", "battalions", {"tone": 5, "type": "entity"}],
  ["battlement", "battlements", {"tone": 5, "type": "object", "subtype": "structure"}],
  ["bear", "bears", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["beast", "beasts", {"tone": 5, "type": "creature", "subtype": "animal"}],
  ["beaver", "beavers", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["bed", "beds", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["bee", "bees", {"tone": 5, "type": "animal", "subtype": "insect"}],
  ["beggar", "beggars", {"tone": 4, "type": "person"}],
  ["bell", "bells", {"tone": 5, "type": "object", "subtype": "instrument"}],
  ["bellboy", "bellboys", {"tone": 5, "type": "person"}],
  ["berry", "berries", {"tone": 5, "type": "consumable", "subtype": "fruit"}],
  ["bicycle", "bicycles", {"tone": 5, "type": "vehicle", "subtype": "ground"}],
  ["bicyclist", "bicyclists", {"tone": 5, "type": "person"}],
  ["biologist", "biologists", {"tone": 5, "type": "person"}],
  ["bird", "birds", {"tone": 5, "type": "creature", "subtype": "animal"}],
  ["bishop", "bishops", {"tone": 5, "type": "person"}],
  ["blacksmith", "blacksmiths", {"tone": 5, "type": "person"}],
  ["boar", "boars", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["boat", "boats", {"tone": 5, "type": "vehicle", "subtype": "water"}],
  ["body builder", "body builders", {"tone": 5, "type": "person"}],
  ["bodyguard", "bodyguards", {"tone": 5, "type": "person"}],
  ["boogeyman", "boogeymen", {"tone": 3, "type": "creature", "subtype": "monster"}],
  ["book", "books", {"tone": 5, "type": "object", "subtype": "writing"}],
  ["boomerang", "boomerangs", {"tone": 5, "type": "object", "subtype": "weapon"}],
  ["booster", "boosters", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["boss", "bosses", {"tone": 5, "type": "person"}],
  ["bottle", "bottles", {"tone": 5, "type": "object", "subtype": "container"}],
  ["box", "boxes", {"tone": 5, "type": "object", "subtype": "container"}],
  ["boxer", "boxers", {"tone": 5, "type": "person"}],
  ["boy", "boys", {"tone": 5, "type": "person"}],
  ["bracelet", "bracelets", {"tone": 5, "type": "clothing", "subtype": "jewelry"}],
  ["brawler", "brawlers", {"tone": 5, "type": "person"}],
  ["bride", "brides", {"tone": 5, "type": "person"}],
  ["bridge", "bridges", {"tone": 5, "type": "object", "subtype": "structure"}],
  ["brother", "brothers", {"tone": 5, "type": "person"}],
  ["bucket", "buckets", {"tone": 5, "type": "object", "subtype": "container"}],
  ["buddy", "buddies", {"tone": 5, "type": "person"}],
  ["buffalo", "buffaloes", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["bug", "bugs", {"tone": 5, "type": "creature", "subtype": "animal"}],
  ["bugle", "bugles", {"tone": 5, "type": "object", "subtype": "instrument"}],
  ["bugler", "buglers", {"tone": 5, "type": "person"}],
  ["builder", "builders", {"tone": 5, "type": "person"}],
  ["bull", "bulls", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["bullet", "bullets", {"tone": 5, "type": "object", "subtype": "weapon"}],
  ["bully", "bullies", {"tone": 3, "type": "person"}],
  ["bundle", "bundles", {"tone": 5, "type": "object", "subtype": "container"}],
  ["burglar", "burglars", {"tone": 3, "type": "person"}],
  ["bus", "buses", {"tone": 5, "type": "vehicle", "subtype": "ground"}],
  ["bush", "bushes", {"tone": 5, "type": "object", "subtype": "plant"}],
  ["businessman", "businessmen", {"tone": 5, "type": "person"}],
  ["bystander", "bystanders", {"tone": 5, "type": "person"}],
  ["cabbage", "cabbages", {"tone": 5, "type": "consumable", "subtype": "vegetable"}],
  ["cable", "cable", {"tone": 5, "type": "component", "subtype": "electronic"}],
  ["cadaver", "cadavers", {"tone": 3, "type": "object"}],
  ["cadet", "cadets", {"tone": 5, "type": "person"}],
  ["cake", "cakes", {"tone": 5, "type": "consumable", "subtype": "dessert"}],
  ["calendar", "calendars", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["caliper", "calipers", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["camel", "camels", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["camera", "cameras", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["cameraman", "cameramen", {"tone": 5, "type": "person"}],
  ["camp", "camps", {"tone": 5, "type": "object", "subtype": "structure"}],
  ["camper", "campers", {"tone": 5, "type": "person"}],
  ["candle", "candles", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["candy", "candies", {"tone": 5, "type": "consumable", "subtype": "dessert"}],
  ["cane", "canes", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["cannon", "cannons", {"tone": 5, "type": "object", "subtype": "weapon"}],
  ["cannonball", "cannonballs", {"tone": 5, "type": "object", "subtype": "weapon"}],
  ["cannoneer", "cannoneers", {"tone": 5, "type": "person"}],
  ["canoe", "canoes", {"tone": 5, "type": "vehicle", "subtype": "water"}],
  ["cantaloupe", "cantaloupes", {"tone": 5, "type": "consumable", "subtype": "fruit"}],
  ["canteen", "canteens", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["cape", "capes", {"tone": 5, "type": "clothing", "subtype": "accessory"}],
  ["captain", "captains", {"tone": 5, "type": "person"}],
  ["car", "cars", {"tone": 5, "type": "vehicle", "subtype": "ground"}],
  ["card", "cards", {"tone": 5, "type": "object", "subtype": "writing"}],
  ["carpenter", "carpenters", {"tone": 5, "type": "person"}],
  ["carrot", "carrots", {"tone": 5, "type": "consumable", "subtype": "vegetable"}],
  ["carton of milk", "cartons of milk", {"tone": 5, "type": "consumable", "subtype": "dairy"}],
  ["cartridge", "cartridges", {"tone": 5, "type": "object", "subtype": "container"}],
  ["castle", "castles", {"tone": 5, "type": "structure", "subtype": "building"}],
  ["cat", "cats", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["celebrity", "celebrities", {"tone": 5, "type": "person"}],
  ["cell", "cells", {"tone": 5, "type": "component", "subtype": "biological"}],
  ["cellist", "cellists", {"tone": 5, "type": "person"}],
  ["cello", "cellos", {"tone": 5, "type": "object", "subtype": "instrument"}],
  ["chair", "chairs", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["chairman", "chairmen", {"tone": 5, "type": "person"}],
  ["champion", "champions", {"tone": 7, "type": "person"}],
  ["chancellor", "chancellors", {"tone": 5, "type": "person"}],
  ["charriot", "charriots", {"tone": 5, "type": "vehicle", "subtype": "ground"}],
  ["charrioteer", "charrioteers", {"tone": 5, "type": "person"}],
  ["chart", "charts", {"tone": 5, "type": "object", "subtype": "writing"}],
  ["checker", "checkers", {"tone": 5, "type": "object", "subtype": "toy"}],
  ["checklist", "checklists", {"tone": 5, "type": "object", "subtype": "writing"}],
  ["cheese", "cheeses", {"tone": 5, "type": "consumable", "subtype": "dairy"}],
  ["cheetah", "cheetahs", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["chef", "chefs", {"tone": 5, "type": "person"}],
  ["chemical", "chemicals", {"tone": 5, "type": "component", "subtype": "elementary"}],
  ["chemist", "chemists", {"tone": 5, "type": "person"}],
  ["chest", "chests", {"tone": 5, "type": "object", "subtype": "container"}],
  ["chick", "chicks", {"tone": 5, "type": "animal", "subtype": "bird"}],
  ["child", "children", {"tone": 5, "type": "person"}],
  ["chimera", "chimeras", {"tone": 5, "type": "creature", "subtype": "monster"}],
  ["chiropractor", "chiropractors", {"tone": 5, "type": "person"}],
  ["chisel", "chisels", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["chocolate", "chocolates", {"tone": 5, "type": "consumable", "subtype": "dessert"}],
  ["choir", "choirs", {"tone": 5, "type": "entity"}],
  ["choreographer", "choreographers", {"tone": 5, "type": "person"}],
  ["cigar", "cigars", {"tone": 5, "type": "consumable", "subtype": "smoke"}],
  ["cigarette", "cigarettes", {"tone": 5, "type": "consumable", "subtype": "smoke"}],
  ["circle", "circles", {"tone": 5, "type": "object", "subtype": "shape"}],
  ["circuit", "circuits", {"tone": 5, "type": "component", "subtype": "electronic"}],
  ["city", "cities", {"tone": 5, "type": "structure", "subtype": "building"}],
  ["clairvoyant", "clairvoyants", {"tone": 5, "type": "person"}],
  ["clam", "clams", {"tone": 5, "type": "animal", "subtype": "fish"}],
  ["clan", "clans", {"tone": 5, "type": "entity"}],
  ["clarinet", "clarinets", {"tone": 5, "type": "object", "subtype": "instrument"}],
  ["class", "classes", {"tone": 5, "type": "entity"}],
  ["clergyman", "clergymen", {"tone": 5, "type": "person"}],
  ["cleric", "clerics", {"tone": 5, "type": "person"}],
  ["clerk", "clerks", {"tone": 5, "type": "person"}],
  ["clicker", "clickers", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["client", "clients", {"tone": 5, "type": "person"}],
  ["climber", "climbers", {"tone": 5, "type": "person"}],
  ["cloak", "cloaks", {"tone": 5, "type": "clothing", "subtype": "top"}],
  ["clock", "clocks", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["clown", "clowns", {"tone": 5, "type": "person"}],
  ["club", "clubs", {"tone": 5, "type": "entity"}],
  ["club", "clubs", {"tone": 5, "type": "object", "subtype": "weapon"}],
  ["coach", "coaches", {"tone": 5, "type": "person"}],
  ["coat", "coats", {"tone": 5, "type": "clothing", "subtype": "top"}],
  ["cockatiel", "cockatiels", {"tone": 5, "type": "animal", "subtype": "bird"}],
  ["cockatoo", "cockatoos", {"tone": 5, "type": "animal", "subtype": "bird"}],
  ["cocktail", "cocktails", {"tone": 5, "type": "food", "subtype": "drink"}],
  ["coffin", "coffins", {"tone": 4, "type": "object", "subtype": "container"}],
  ["coin", "coins", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["college", "colleges", {"tone": 5, "type": "structure", "subtype": "building"}],
  ["collie", "collies", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["colt", "colts", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["comb", "combs", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["combine", "combines", {"tone": 5, "type": "vehicle", "subtype": "ground"}],
  ["comedian", "comedians", {"tone": 5, "type": "person"}],
  ["comet", "comets", {"tone": 5, "type": "object", "subtype": "stellar"}],
  ["comma", "commas", {"tone": 5, "type": "component", "subtype": "writing"}],
  ["commando", "commandos", {"tone": 5, "type": "person"}],
  ["comment", "comments", {"tone": 5, "type": "object", "subtype": "writing"}],
  ["commentator", "commentators", {"tone": 5, "type": "person"}],
  ["communicator", "communicators", {"tone": 5, "type": "person"}],
  ["company", "companies", {"tone": 5, "type": "entity"}],
  ["compiler", "compilers", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["composer", "composers", {"tone": 5, "type": "person"}],
  ["computer", "computers", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["cone", "cones", {"tone": 5, "type": "object", "subtype": "shape"}],
  ["consultant", "consultants", {"tone": 5, "type": "person"}],
  ["consumer", "consumers", {"tone": 5, "type": "person"}],
  ["contact", "contacts", {"tone": 5, "type": "person"}],
  ["container", "containers", {"tone": 5, "type": "object", "subtype": "container"}],
  ["contract", "contracts", {"tone": 5, "type": "object", "subtype": "writing"}],
  ["contractor", "contractors", {"tone": 5, "type": "person"}],
  ["controller", "controllers", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["convict", "convicts", {"tone": 3, "type": "person"}],
  ["cookie", "cookies", {"tone": 5, "type": "food", "subtype": "dessert"}],
  ["cop", "cops", {"tone": 4, "type": "person"}],
  ["core", "cores", {"tone": 5, "type": "component", "subtype": "general"}],
  ["corgi", "corgis", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["cork", "corks", {"tone": 5, "type": "component", "subtype": "material"}],
  ["corkscrew", "corkscrews", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["coroner", "coroners", {"tone": 5, "type": "person"}],
  ["counselors", "counselors", {"tone": 5, "type": "person"}],
  ["counter", "counters", {"tone": 5, "type": "object", "subtype": "structure"}],
  ["country", "countries", {"tone": 5, "type": "entity"}],
  ["couple", "couples", {"tone": 5, "type": "entity"}],
  ["cow", "cows", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["coward", "cowards", {"tone": 3, "type": "person"}],
  ["cowboy", "cowboys", {"tone": 5, "type": "person"}],
  ["coyote", "coyotes", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["crab", "crabs", {"tone": 5, "type": "animal", "subtype": "fish"}],
  ["crate", "crates", {"tone": 5, "type": "object", "subtype": "container"}],
  ["creature", "creatures", {"tone": 5, "type": "creature", "subtype": "general"}],
  ["creep", "creeps", {"tone": 3, "type": "person"}],
  ["crepe", "crepes", {"tone": 5, "type": "food", "subtype": "meal"}],
  ["crescent", "crescents", {"tone": 5, "type": "object", "subtype": "shape"}],
  ["criminal", "criminals", {"tone": 3, "type": "person"}],
  ["crowd", "crowds", {"tone": 5, "type": "entity"}],
  ["crown", "crowns", {"tone": 5, "type": "clothing", "subtype": "hat"}],
  ["crucifix", "crucifixes", {"tone": 5, "type": "object", "subtype": "decoration"}],
  ["crusader", "crusaders", {"tone": 5, "type": "person"}],
  ["crusher", "crushers", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["crystal", "crystals", {"tone": 5, "type": "component", "subtype": "mineral"}],
  ["cultist", "cultists", {"tone": 4, "type": "person"}],
  ["cup", "cups", {"tone": 5, "type": "object", "subtype": "container"}],
  ["curse", "curses", {"tone": 2, "type": "object", "subtype": "writing"}],
  ["cushion", "cushions", {"tone": 5, "type": "object", "subtype": "decoration"}],
  ["cutthroat", "cutthroats", {"tone": 3, "type": "person"}],
  ["cyclist", "cyclists", {"tone": 5, "type": "person"}],
  ["cylinder", "cylinders", {"tone": 5, "type": "object", "subtype": "shape"}],
  ["dagger", "daggers", {"tone": 5, "type": "object", "subtype": "weapon"}],
  ["dancer", "dancers", {"tone": 5, "type": "person"}],
  ["dandelion", "dandelions", {"tone": 5, "type": "object", "subtype": "plant"}],
  ["deacon", "deacons", {"tone": 5, "type": "person"}],
  ["dealer", "dealers", {"tone": 5, "type": "person"}],
  ["debaters", "debaters", {"tone": 5, "type": "person"}],
  ["decibel", "decibels", {"tone": 5, "type": "component", "subtype": "physical"}],
  ["decimal", "decimals", {"tone": 5, "type": "component", "subtype": "writing"}],
  ["decoration", "decorations", {"tone": 5, "type": "object", "subtype": "decoration"}],
  ["deer", "deer", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["deity", "deities", {"tone": 6, "type": "creature", "subtype": "holy"}],
  ["demon", "demons", {"tone": 2, "type": "creature", "subtype": "monster"}],
  ["dentist", "dentists", {"tone": 5, "type": "person"}],
  ["dermatologist", "dermatologists", {"tone": 5, "type": "person"}],
  ["designer", "designers", {"tone": 5, "type": "person"}],
  ["desk", "desks", {"tone": 5, "type": "object", "subtype": "structure"}],
  ["despot", "despots", {"tone": 3, "type": "person"}],
  ["dessert", "desserts", {"tone": 5, "type": "food", "subtype": "dessert"}],
  ["destroyer", "destroyers", {"tone": 4, "type": "person"}],
  ["developer", "developers", {"tone": 5, "type": "person"}],
  ["devil", "devils", {"tone": 3, "type": "creature", "subtype": "monster"}],
  ["diamond", "diamonds", {"tone": 5, "type": "component", "subtype": "mineral"}],
  ["diary", "diaries", {"tone": 5, "type": "object", "subtype": "writing"}],
  ["dictator", "dictator", {"tone": 3, "type": "person"}],
  ["die", "dice", {"tone": 5, "type": "object", "subtype": "toy"}],
  ["digit", "digits", {"tone": 5, "type": "component", "subtype": "writing"}],
  ["dime", "dimes", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["dinghy", "dinghys", {"tone": 5, "type": "vehicle", "subtype": "water"}],
  ["dingo", "dingoes", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["dinosaur", "dinosaurs", {"tone": 5, "type": "animal", "subtype": "reptile"}],
  ["director", "directors", {"tone": 5, "type": "person"}],
  ["disc", "discs", {"tone": 5, "type": "object", "subtype": "shape"}],
  ["disciple", "disciples", {"tone": 5, "type": "person"}],
  ["disk", "disks", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["dissenter", "dissenters", {"tone": 5, "type": "person"}],
  ["diver", "divers", {"tone": 5, "type": "person"}],
  ["doctor", "doctors", {"tone": 5, "type": "person"}],
  ["dog", "dogs", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["doll", "dolls", {"tone": 5, "type": "object", "subtype": "toy"}],
  ["dollar", "dollars", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["dolphin", "dolphins", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["dome", "domes", {"tone": 5, "type": "object", "subtype": "shape"}],
  ["donkey", "donkeys", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["door", "doors", {"tone": 5, "type": "object", "subtype": "structure"}],
  ["dot", "dots", {"tone": 5, "type": "object", "subtype": "shape"}],
  ["doubt", "doubts", {"tone": 5, "type": "event", "subtype": "internal"}],
  ["dove", "doves", {"tone": 5, "type": "animal", "subtype": "bird"}],
  ["dragon", "dragons", {"tone": 5, "type": "creature", "subtype": "monster"}],
  ["dream", "dreams", {"tone": 5, "type": "event", "subtype": "internal"}],
  ["dress", "dresses", {"tone": 5, "type": "clothing", "subtype": "full"}],
  ["drifter", "drifters", {"tone": 4, "type": "person"}],
  ["drink", "drinks", {"tone": 5, "type": "food", "subtype": "drink"}],
  ["driver", "drivers", {"tone": 5, "type": "person"}],
  ["drone", "drones", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["drum", "drums", {"tone": 5, "type": "object", "subtype": "instrument"}],
  ["drunk", "drunks", {"tone": 3, "type": "person"}],
  ["duck", "ducks", {"tone": 5, "type": "animal", "subtype": "bird"}],
  ["dwarf", "dwarves", {"tone": 5, "type": "person", "subtype": "fantasy"}],
  ["eagle", "eagles", {"tone": 5, "type": "animal", "subtype": "bird"}],
  ["ear", "ears", {"tone": 5, "type": "component", "subtype": "biological"}],
  ["earthquake", "earthquakes", {"tone": 5, "type": "event", "subtype": "natural"}],
  ["echo", "echoes", {"tone": 5, "type": "event", "subtype": "external"}],
  ["eclipse", "eclipses", {"tone": 5, "type": "event", "subtype": "natural"}],
  ["editor", "editors", {"tone": 5, "type": "person"}],
  ["eel", "eels", {"tone": 5, "type": "animal", "subtype": "fish"}],
  ["egg", "eggs", {"tone": 5, "type": "food", "subtype": "poultry"}],
  ["elder", "elders", {"tone": 5, "type": "person"}],
  ["electron", "electrons", {"tone": 5, "type": "component", "subtype": "elementary"}],
  ["element", "elements", {"tone": 5, "type": "component", "subtype": "elementary"}],
  ["elephant", "elephants", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["elf", "elves", {"tone": 5, "type": "person", "subtype": "fantasy"}],
  ["elitist", "elitists", {"tone": 4, "type": "person"}],
  ["elk", "elk", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["ellipsoid", "ellipsoids", {"tone": 5, "type": "object", "subtype": "shape"}],
  ["emerald", "emeralds", {"tone": 5, "type": "component", "subtype": "mineral"}],
  ["emotion", "emotions", {"tone": 5, "type": "event", "subtype": "internal"}],
  ["emperor penguin", "emperor penguins", {"tone": 5, "type": "animal", "subtype": "bird"}],
  ["emperor", "emperors", {"tone": 5, "type": "person"}],
  ["engineer", "engineers", {"tone": 5, "type": "person"}],
  ["eraser", "erasers", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["error", "errors", {"tone": 4, "type": "event", "subtype": "action"}],
  ["executioner", "executioners", {"tone": 4, "type": "person"}],
  ["explorer", "explorers", {"tone": 5, "type": "person"}],
  ["explosion", "explosions", {"tone": 5, "type": "event", "subtype": "action"}],
  ["extrovert", "extroverts", {"tone": 5, "type": "person"}],
  ["eye", "eyes", {"tone": 5, "type": "component", "subtype": "biological"}],
  ["eyeball", "eyeballs", {"tone": 5, "type": "component", "subtype": "biological"}],
  ["eyebrow", "eyebrows", {"tone": 5, "type": "component", "subtype": "biological"}],
  ["eyelid", "eyelids", {"tone": 5, "type": "component", "subtype": "biological"}],
  ["face", "faces", {"tone": 5, "type": "component", "subtype": "biological"}],
  ["factory", "factories", {"tone": 5, "type": "structure", "subtype": "building"}],
  ["failure", "failures", {"tone": 3, "type": "event", "subtype": "action"}],
  ["faker", "fakers", {"tone": 4, "type": "person"}],
  ["falcon", "falcons", {"tone": 5, "type": "animal", "subtype": "bird"}],
  ["fallacy", "fallacies", {"tone": 4, "type": "event", "subtype": "action"}],
  ["farmer", "farmers", {"tone": 5, "type": "person"}],
  ["feather", "feathers", {"tone": 5, "type": "component", "subtype": "biological"}],
  ["fedora", "fedoras", {"tone": 5, "type": "clothing", "subtype": "hat"}],
  ["feeling", "feelings", {"tone": 5, "type": "event", "subtype": "internal"}],
  ["felon", "felons", {"tone": 3, "type": "person"}],
  ["fencer", "fencers", {"tone": 5, "type": "person"}],
  ["field", "fields", {"tone": 5, "type": "object", "subtype": "structure"}],
  ["fighter", "fighters", {"tone": 5, "type": "person"}],
  ["film", "films", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["finger", "fingers", {"tone": 5, "type": "component", "subtype": "biological"}],
  ["fireman", "firemen", {"tone": 5, "type": "person"}],
  ["fish", "fish", {"tone": 5, "type": "animal", "subtype": "fish"}],
  ["fisherman", "fishermen", {"tone": 5, "type": "person"}],
  ["flail", "flails", {"tone": 5, "type": "object", "subtype": "weapon"}],
  ["flame", "flames", {"tone": 5, "type": "component", "subtype": "elementary"}],
  ["flavor", "flavors", {"tone": 5, "type": "event", "subtype": "internal"}],
  ["floater", "floaters", {"tone": 5, "type": "object", "subtype": "general"}],
  ["florist", "florists", {"tone": 5, "type": "person"}],
  ["flower", "flowers", {"tone": 5, "type": "object", "subtype": "plant"}],
  ["flute", "flutes", {"tone": 5, "type": "object", "subtype": "instrument"}],
  ["flutist", "flutists", {"tone": 5, "type": "person"}],
  ["fly", "flies", {"tone": 5, "type": "animal", "subtype": "insect"}],
  ["foal", "foals", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["folder", "folders", {"tone": 5, "type": "object", "subtype": "container"}],
  ["foot", "feet", {"tone": 5, "type": "component", "subtype": "biological"}],
  ["football", "footballs", {"tone": 5, "type": "object", "subtype": "toy"}],
  ["forklift", "forklifts", {"tone": 5, "type": "vehicle", "subtype": "ground"}],
  ["fox", "fox", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["fraction", "fractions", {"tone": 5, "type": "component", "subtype": "writing"}],
  ["fragment", "fragments", {"tone": 5, "type": "component", "subtype": "writing"}],
  ["freighter", "freighter", {"tone": 5, "type": "vehicle", "subtype": "water"}],
  ["friend", "friends", {"tone": 7, "type": "person"}],
  ["frog", "frogs", {"tone": 5, "type": "animal", "subtype": "amphibian"}],
  ["fuse", "fuses", {"tone": 5, "type": "component", "subtype": "electrical"}],
  ["gadget", "gadgets", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["gag", "gags", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["game", "games", {"tone": 5, "type": "event", "subtype": "external"}],
  ["gang", "gangs", {"tone": 4, "type": "entity"}],
  ["gangster", "gangsters", {"tone": 4, "type": "person"}],
  ["gardener", "gardeners", {"tone": 5, "type": "person"}],
  ["gardenia", "gardenias", {"tone": 5, "type": "object", "subtype": "plant"}],
  ["garlic clove", "garlic cloves", {"tone": 5, "type": "food", "subtype": "vegetable"}],
  ["garment", "garments", {"tone": 5, "type": "clothing", "subtype": "full"}],
  ["garnet", "garnets", {"tone": 5, "type": "component", "subtype": "mineral"}],
  ["gate", "gates", {"tone": 5, "type": "object", "subtype": "structure"}],
  ["gatling gun", "gatling guns", {"tone": 5, "type": "object", "subtype": "weapon"}],
  ["gauntlet", "gauntlets", {"tone": 5, "type": "clothing", "subtype": "armor"}],
  ["gazelle", "gazelles", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["gem", "gems", {"tone": 5, "type": "component", "subtype": "mineral"}],
  ["generator", "generators", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["genie", "genies", {"tone": 5, "type": "creature", "subtype": "general"}],
  ["gentleman", "gentlemen", {"tone": 5, "type": "person"}],
  ["geranium", "geraniums", {"tone": 5, "type": "object", "subtype": "plant"}],
  ["germ", "germs", {"tone": 3, "type": "component", "subtype": "biological"}],
  ["ghost", "ghosts", {"tone": 5, "type": "creature", "subtype": "monster"}],
  ["ghoul", "ghouls", {"tone": 3, "type": "creature", "subtype": "monster"}],
  ["giant", "giants", {"tone": 5, "type": "person", "subtype": "fantasy"}],
  ["giblet", "giblets", {"tone": 5, "type": "component", "subtype": "biological"}],
  ["ginger root", "ginger roots", {"tone": 5, "type": "food", "subtype": "vegetable"}],
  ["girdle", "girdles", {"tone": 5, "type": "clothing", "subtype": "underwear"}],
  ["gladiator", "gladiators", {"tone": 5, "type": "person"}],
  ["glider", "gliders", {"tone": 5, "type": "vehicle", "subtype": "air"}],
  ["gnome", "gnomes", {"tone": 5, "type": "person", "subtype": "fantasy"}],
  ["goat", "goats", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["goblin", "goblins", {"tone": 5, "type": "creature", "subtype": "monster"}],
  ["god", "gods", {"tone": 5, "type": "creature", "subtype": "holy"}],
  ["gold bar", "gold bars", {"tone": 5, "type": "object", "subtype": "tool"}],
  ["goldfish", "goldfish", {"tone": 5, "type": "animal", "subtype": "fish"}],
  ["golf ball", "golf balls", {"tone": 5, "type": "object", "subtype": "toy"}],
  ["golfer", "golfers", {"tone": 5, "type": "person"}],
  ["goose", "geese", {"tone": 5, "type": "animal", "subtype": "bird"}],
  ["gorilla", "gorillas", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["governor", "governors", {"tone": 5, "type": "person"}],
  ["grain of rice", "rice", {"tone": 5, "type": "food", "subtype": "grain"}],
  ["grape", "grapes", {"tone": 5, "type": "food", "subtype": "fruit"}],
  ["grapefruit", "grapefruits", {"tone": 5, "type": "food", "subtype": "fruit"}],
  ["graph", "graphs", {"tone": 5, "type": "object", "subtype": "writing"}],
  ["grave", "graves", {"tone": 5, "type": "object", "subtype": "structure"}],
  ["green bean", "green beans", {"tone": 5, "type": "food", "subtype": "vegetable"}],
  ["grinch", "grinches", {"tone": 5, "type": "person"}],
  ["grizzly bear", "grizzly bears", {"tone": 5, "type": "animal", "subtype": "mammal"}],
  ["guardian", "guardians", {"tone": 5, "type": "person"}],
  ["guest", "guests", {"tone": 5, "type": "person"}],
  ["guide", "guides", {"tone": 5, "type": "person"}],
  ["guidebook", "guidebooks", {"tone": 5, "type": "object", "subtype": "writing"}],
  ["guitar", "guitars", {"tone": 5, "type": "object", "subtype": "instrument"}],

  ["guitarist", "guitarists", {"tone": 5, "type": "object"}],
  ["gull", "gulls", {"tone": 5, "type": "object"}],
  ["gun", "guns", {"tone": 5, "type": "object"}],
  ["gunfighter", "gunfighters", {"tone": 5, "type": "object"}],
  ["gunman", "gunmen", {"tone": 5, "type": "object"}],
  ["guru", "gurus", {"tone": 5, "type": "object"}],
  ["gymnast", "gymnasts", {"tone": 5, "type": "object"}],
  ["hacker", "hackers", {"tone": 5, "type": "object"}],
  ["hacksaw", "hacksaws", {"tone": 5, "type": "object"}],
  ["hailstone", "hailstones", {"tone": 5, "type": "object"}],
  ["halo", "halos", {"tone": 5, "type": "object"}],
  ["ham", "hams", {"tone": 5, "type": "object"}],
  ["hamburger", "hamburgers", {"tone": 5, "type": "object"}],
  ["hammer", "hammers", {"tone": 5, "type": "object"}],
  ["hamster", "hamsters", {"tone": 5, "type": "object"}],
  ["hand", "hands", {"tone": 5, "type": "object"}],
  ["handbag", "handbags", {"tone": 5, "type": "object"}],
  ["handgun", "handguns", {"tone": 5, "type": "object"}],
  ["handle", "handles", {"tone": 5, "type": "object"}],
  ["hare", "hares", {"tone": 5, "type": "object"}],
  ["harp", "harps", {"tone": 5, "type": "object"}],
  ["harpsichord", "harpsichords", {"tone": 5, "type": "object"}],
  ["harpsichordist", "harpsichordists", {"tone": 5, "type": "object"}],
  ["hat", "hats", {"tone": 5, "type": "object"}],
  ["hatchet", "hatchets", {"tone": 5, "type": "object"}],
  ["hatchling", "hatchlings", {"tone": 5, "type": "object"}],
  ["hawk", "hawks", {"tone": 5, "type": "object"}],
  ["haystack", "haystacks", {"tone": 5, "type": "object"}],
  ["hazelnut", "hazelnuts", {"tone": 5, "type": "object"}],
  ["head", "heads", {"tone": 5, "type": "object"}],
  ["headline", "headlines", {"tone": 5, "type": "object"}],
  ["healer", "healers", {"tone": 5, "type": "object"}],
  ["heart", "hearts", {"tone": 5, "type": "object"}],
  ["hedgehog", "hedgehogs", {"tone": 5, "type": "object"}],
  ["helecopter", "helecopters", {"tone": 5, "type": "object"}],
  ["helmet", "helmets", {"tone": 5, "type": "object"}],
  ["helper", "helpers", {"tone": 5, "type": "object"}],
  ["henchman", "henchmen", {"tone": 5, "type": "object"}],
  ["henchwoman", "henchwomen", {"tone": 5, "type": "object"}],
  ["herald", "heralds", {"tone": 5, "type": "object"}],
  ["hero", "heroes", {"tone": 5, "type": "object"}],
  ["heroine", "heroines", {"tone": 5, "type": "object"}],
  ["herring", "herrings", {"tone": 5, "type": "object"}],
  ["hex", "hexes", {"tone": 5, "type": "object"}],
  ["hexagon", "hexagons", {"tone": 5, "type": "object"}],
  ["hick", "hicks", {"tone": 5, "type": "object"}],
  ["highwayman", "highwaymen", {"tone": 5, "type": "object"}],
  ["hiker", "hikers", {"tone": 5, "type": "object"}],
  ["hill", "hills", {"tone": 5, "type": "object"}],
  ["hillbilly", "hillbillies", {"tone": 5, "type": "object"}],
  ["hint", "hints", {"tone": 5, "type": "object"}],
  ["hipster", "hipsters", {"tone": 5, "type": "object"}],
  ["hitchhiker", "hitchhikers", {"tone": 5, "type": "object"}],
  ["hobbit", "hobbits", {"tone": 5, "type": "object"}],
  ["hobo", "hobos", {"tone": 5, "type": "object"}],
  ["hockey puck", "hockey pucks", {"tone": 5, "type": "object"}],
  ["honeybee", "honeybees", {"tone": 5, "type": "object"}],
  ["honeysuckle flower", "honeysuckle flowers", {"tone": 5, "type": "object"}],
  ["hood", "hoods", {"tone": 5, "type": "object"}],
  ["hoodlum", "hoodlums", {"tone": 5, "type": "object"}],
  ["hook", "hooks", {"tone": 5, "type": "object"}],
  ["hookworm", "hookworms", {"tone": 5, "type": "object"}],
  ["hooligan", "hooligans", {"tone": 5, "type": "object"}],
  ["hormone", "hormones", {"tone": 5, "type": "object"}],
  ["horn", "horns", {"tone": 5, "type": "object"}],
  ["horse", "horses", {"tone": 5, "type": "object"}],
  ["horseman", "horsemen", {"tone": 5, "type": "object"}],
  ["horsewoman", "horsewomen", {"tone": 5, "type": "object"}],
  ["host", "hosts", {"tone": 5, "type": "object"}],
  ["hostage", "hostages", {"tone": 5, "type": "object"}],
  ["hound", "hounds", {"tone": 5, "type": "object"}],
  ["huckster", "hucksters", {"tone": 5, "type": "object"}],
  ["hunchback", "hunchbacks", {"tone": 5, "type": "object"}],
  ["hunter", "hunters", {"tone": 5, "type": "object"}],
  ["hurricane", "hurricanes", {"tone": 5, "type": "object"}],
  ["hustler", "hustlers", {"tone": 5, "type": "object"}],
  ["hyena", "hyenas", {"tone": 5, "type": "object"}],
  ["hymn", "hymns", {"tone": 5, "type": "object"}],
  ["ice cube", "ice cubes", {"tone": 5, "type": "object"}],
  ["idea", "ideas", {"tone": 5, "type": "object"}],
  ["idiot", "idiots", {"tone": 5, "type": "object"}],
  ["idol", "idols", {"tone": 5, "type": "object"}],
  ["iguana", "iguanas", {"tone": 5, "type": "object"}],
  ["image", "images", {"tone": 5, "type": "object"}],
  ["infant", "infants", {"tone": 5, "type": "object"}],
  ["infantryman", "infantrymen", {"tone": 5, "type": "object"}],
  ["ingredient", "ingredients", {"tone": 5, "type": "object"}],
  ["injury", "injuries", {"tone": 5, "type": "object"}],
  ["insect", "insects", {"tone": 5, "type": "object"}],
  ["inspector", "inspectors", {"tone": 5, "type": "object"}],
  ["insult", "insults", {"tone": 5, "type": "object"}],
  ["integer", "integers", {"tone": 5, "type": "object"}],
  ["intellectual", "intellectuals", {"tone": 5, "type": "object"}],
  ["interrogator", "interrogators", {"tone": 5, "type": "object"}],
  ["intestine", "intestines", {"tone": 5, "type": "object"}],
  ["intruder", "intruders", {"tone": 5, "type": "object"}],
  ["invader", "invaders", {"tone": 5, "type": "object"}],
  ["inventor", "inventors", {"tone": 5, "type": "object"}],
  ["investor", "investors", {"tone": 5, "type": "object"}],
  ["ion", "ions", {"tone": 5, "type": "object"}],
  ["iron bar", "iron bars", {"tone": 5, "type": "object"}],
  ["iron pot", "iron pots", {"tone": 5, "type": "object"}],
  ["iron rod", "iron rods", {"tone": 5, "type": "object"}],
  ["jacket", "jackets", {"tone": 5, "type": "object"}],
  ["jaguar", "jaguars", {"tone": 5, "type": "object"}],
  ["janitor", "janitors", {"tone": 5, "type": "object"}],
  ["jar of jam", "jars of jam", {"tone": 5, "type": "object"}],
  ["jar of jelly", "jars of jelly", {"tone": 5, "type": "object"}],
  ["jar", "jars", {"tone": 5, "type": "object"}],
  ["javelin", "javelins", {"tone": 5, "type": "object"}],
  ["jawbone", "jawbones", {"tone": 5, "type": "object"}],
  ["jet", "jets", {"tone": 5, "type": "object"}],
  ["jewel", "jewels", {"tone": 5, "type": "object"}],
  ["job", "jobs", {"tone": 5, "type": "object"}],
  ["jockey", "jockeys", {"tone": 5, "type": "object"}],
  ["joke", "jokes", {"tone": 5, "type": "object"}],
  ["journal", "journals", {"tone": 5, "type": "object"}],
  ["journeyman", "journeymen", {"tone": 5, "type": "object"}],
  ["jouster", "jousters", {"tone": 5, "type": "object"}],
  ["judge", "judges", {"tone": 5, "type": "object"}],
  ["juggler", "jugglers", {"tone": 5, "type": "object"}],
  ["juror", "jurors", {"tone": 5, "type": "object"}],
  ["kabob", "kabobs", {"tone": 5, "type": "object"}],
  ["kaiser", "kaisers", {"tone": 5, "type": "object"}],
  ["kale leaf", "kale", {"tone": 5, "type": "object"}],
  ["kaleidoscope", "kaleidoscope", {"tone": 5, "type": "object"}],
  ["kangaroo", "kangaroos", {"tone": 5, "type": "object"}],
  ["kazoo", "kazoos", {"tone": 5, "type": "object"}],
  ["keg", "kegs", {"tone": 5, "type": "object"}],
  ["key", "keys", {"tone": 5, "type": "object"}],
  ["khan", "khans", {"tone": 5, "type": "object"}],
  ["killer", "killers", {"tone": 5, "type": "object"}],
  ["king", "kings", {"tone": 5, "type": "object"}],
  ["kitchen", "kitchens", {"tone": 5, "type": "object"}],
  ["kitten", "kittens", {"tone": 5, "type": "object"}],
  ["kneecap", "kneecaps", {"tone": 5, "type": "object"}],
  ["knight", "knights", {"tone": 5, "type": "object"}],
  ["koala", "koalas", {"tone": 5, "type": "object"}],
  ["kung-fu fighter", "kung-fu fighters", {"tone": 5, "type": "object"}],
  ["ladder", "ladders", {"tone": 5, "type": "object"}],
  ["ladle", "ladles", {"tone": 5, "type": "object"}],
  ["lady", "ladies", {"tone": 5, "type": "object"}],
  ["lamb", "lambs", {"tone": 5, "type": "object"}],
  ["lamp", "lamps", {"tone": 5, "type": "object"}],
  ["lance", "lances", {"tone": 5, "type": "object"}],
  ["lantern", "lanterns", {"tone": 5, "type": "object"}],
  ["lark", "larks", {"tone": 5, "type": "object"}],
  ["larva", "larvae", {"tone": 5, "type": "object"}],
  ["lawyer", "lawyers", {"tone": 5, "type": "object"}],
  ["leaf", "leaves", {"tone": 5, "type": "object"}],
  ["liar", "liars", {"tone": 5, "type": "object"}],
  ["librarian", "librarians", {"tone": 5, "type": "object"}],
  ["lie", "lies", {"tone": 5, "type": "object"}],
  ["lighter", "lighters", {"tone": 5, "type": "object"}],
  ["lime", "limes", {"tone": 5, "type": "object"}],
  ["line", "lines", {"tone": 5, "type": "object"}],
  ["list", "lists", {"tone": 5, "type": "object"}],
  ["llama", "llamas", {"tone": 5, "type": "object"}],
  ["lobster", "lobsters", {"tone": 5, "type": "object"}],
  ["lock", "locks", {"tone": 5, "type": "object"}],
  ["locust", "locusts", {"tone": 5, "type": "object"}],
  ["log", "logs", {"tone": 5, "type": "object"}],
  ["loon", "loons", {"tone": 5, "type": "object"}],
  ["lord", "lords", {"tone": 5, "type": "object"}],
  ["louse", "lice", {"tone": 5, "type": "object"}],
  ["lover", "lovers", {"tone": 5, "type": "object"}],
  ["lumberjack", "lumberjacks", {"tone": 5, "type": "object"}],
  ["lunar lander", "lunar landers", {"tone": 5, "type": "object"}],
  ["lung", "lungs", {"tone": 5, "type": "object"}],
  ["lure", "lures", {"tone": 5, "type": "object"}],
  ["machine gun", "machine guns", {"tone": 5, "type": "object"}],
  ["machine", "machines", {"tone": 5, "type": "object"}],
  ["mackerel", "mackerels", {"tone": 5, "type": "object"}],
  ["magazine", "magazines", {"tone": 5, "type": "object"}],
  ["magician", "magicians", {"tone": 5, "type": "object"}],
  ["magnet", "magnets", {"tone": 5, "type": "object"}],
  ["mailman", "mailmen", {"tone": 5, "type": "object"}],
  ["maniac", "maniacs", {"tone": 5, "type": "object"}],
  ["mannequin", "mannequins", {"tone": 5, "type": "object"}],
  ["marble", "marbles", {"tone": 5, "type": "object"}],
  ["marine", "marines", {"tone": 5, "type": "object"}],
  ["marker", "markers", {"tone": 5, "type": "object"}],
  ["marksman", "marksmen", {"tone": 5, "type": "object"}],
  ["mask", "masks", {"tone": 5, "type": "object"}],
  ["meal", "meals", {"tone": 5, "type": "object"}],
  ["medal", "medals", {"tone": 5, "type": "object"}],
  ["medium", "mediums", {"tone": 5, "type": "object"}],
  ["meeting", "meetings", {"tone": 5, "type": "object"}],
  ["melon", "melons", {"tone": 5, "type": "object"}],
  ["merchant", "merchants", {"tone": 5, "type": "object"}],
  ["mermaid", "mermaids", {"tone": 5, "type": "object"}],
  ["message", "messages", {"tone": 5, "type": "object"}],
  ["method", "methods", {"tone": 5, "type": "object"}],
  ["microbe", "microbes", {"tone": 5, "type": "object"}],
  ["microphone", "microphones", {"tone": 5, "type": "object"}],
  ["mink", "minks", {"tone": 5, "type": "object"}],
  ["mirror", "mirrors", {"tone": 5, "type": "object"}],
  ["missile", "missiles", {"tone": 5, "type": "object"}],
  ["model", "models", {"tone": 5, "type": "object"}],
  ["mole", "moles", {"tone": 5, "type": "object"}],
  ["monk", "monks", {"tone": 5, "type": "object"}],
  ["monkey", "monkeys", {"tone": 5, "type": "object"}],
  ["monster", "monsters", {"tone": 5, "type": "object"}],
  ["monument", "monuments", {"tone": 5, "type": "object"}],
  ["moon", "moons", {"tone": 5, "type": "object"}],
  ["mosquito", "mosquitoes", {"tone": 5, "type": "object"}],
  ["moth", "moths", {"tone": 5, "type": "object"}],
  ["motor", "motors", {"tone": 5, "type": "object"}],
  ["mouse", "mice", {"tone": 5, "type": "object"}],
  ["moustache", "moustaches", {"tone": 5, "type": "object"}],
  ["mouth", "mouths", {"tone": 5, "type": "object"}],
  ["murderer", "murderers", {"tone": 5, "type": "object"}],
  ["mushroom", "mushrooms", {"tone": 5, "type": "object"}],
  ["musket", "muskets", {"tone": 5, "type": "object"}],
  ["mystic", "mystics", {"tone": 5, "type": "object"}],
  ["narwal", "narwals", {"tone": 5, "type": "object"}],
  ["nebula", "nebulas", {"tone": 5, "type": "object"}],
  ["neck", "necks", {"tone": 5, "type": "object"}],
  ["necklace", "necklaces", {"tone": 5, "type": "object"}],
  ["necromancer", "necromancers", {"tone": 5, "type": "object"}],
  ["needle", "needles", {"tone": 5, "type": "object"}],
  ["net", "nets", {"tone": 5, "type": "object"}],
  ["neuromancer", "neuromancers", {"tone": 5, "type": "object"}],
  ["newspaper", "newspapers", {"tone": 5, "type": "object"}],
  ["newt", "newts", {"tone": 5, "type": "object"}],
  ["nightingale", "nightingales", {"tone": 5, "type": "object"}],
  ["nightmare", "nightmares", {"tone": 5, "type": "object"}],
  ["ninja", "ninjas", {"tone": 5, "type": "object"}],
  ["nobleman", "noblemen", {"tone": 5, "type": "object"}],
  ["novel", "novels", {"tone": 5, "type": "object"}],
  ["novelist", "novelists", {"tone": 5, "type": "object"}],
  ["number", "numbers", {"tone": 5, "type": "object"}],
  ["nun", "nuns", {"tone": 5, "type": "object"}],
  ["nurse", "nurses", {"tone": 5, "type": "object"}],
  ["nut", "nuts", {"tone": 5, "type": "object"}],
  ["nutshell", "nutshells", {"tone": 5, "type": "object"}],
  ["nymph", "nymphs", {"tone": 5, "type": "object"}],
  ["obelisk", "obelisks", {"tone": 5, "type": "object"}],
  ["ocarina", "ocarinas", {"tone": 5, "type": "object"}],
  ["ocelot", "ocelots", {"tone": 5, "type": "object"}],
  ["octopus", "octopuses", {"tone": 5, "type": "object"}],
  ["odor", "odors", {"tone": 5, "type": "object"}],
  ["officer", "officers", {"tone": 5, "type": "object"}],
  ["olive", "olives", {"tone": 5, "type": "object"}],
  ["omelet", "omelets", {"tone": 5, "type": "object"}],
  ["omen", "omens", {"tone": 5, "type": "object"}],
  ["onion", "onions", {"tone": 5, "type": "object"}],
  ["oracle", "oracles", {"tone": 5, "type": "object"}],
  ["orator", "orators", {"tone": 5, "type": "object"}],
  ["orphan", "orphans", {"tone": 5, "type": "object"}],
  ["otter", "otters", {"tone": 5, "type": "object"}],
  ["outcast", "outcasts", {"tone": 5, "type": "object"}],
  ["outlaw", "outlaws", {"tone": 5, "type": "object"}],
  ["outsider", "outsiders", {"tone": 5, "type": "object"}],
  ["oval", "ovals", {"tone": 5, "type": "object"}],
  ["oven", "ovens", {"tone": 5, "type": "object"}],
  ["overseer", "overseers", {"tone": 5, "type": "object"}],
  ["owl", "owls", {"tone": 5, "type": "object"}],
  ["oyster", "oysters", {"tone": 5, "type": "object"}],
  ["pacifier", "pacifiers", {"tone": 5, "type": "object"}],
  ["padlock", "padlocks", {"tone": 5, "type": "object"}],
  ["page", "pages", {"tone": 5, "type": "object"}],
  ["paintbrush", "paintbrushes", {"tone": 5, "type": "object"}],
  ["painting", "paintings", {"tone": 5, "type": "object"}],
  ["pansy", "pansies", {"tone": 5, "type": "object"}],
  ["paper", "papers", {"tone": 5, "type": "object"}],
  ["parasite", "parasites", {"tone": 5, "type": "object"}],
  ["peach", "peaches", {"tone": 5, "type": "object"}],
  ["peacock", "peacocks", {"tone": 5, "type": "object"}],
  ["peanut", "peanuts", {"tone": 5, "type": "object"}],
  ["pear", "pears", {"tone": 5, "type": "object"}],
  ["pearl", "pearls", {"tone": 5, "type": "object"}],
  ["peasant", "peasants", {"tone": 5, "type": "object"}],
  ["pebble", "pebbles", {"tone": 5, "type": "object"}],
  ["pecan", "pecans", {"tone": 5, "type": "object"}],
  ["pen", "pens", {"tone": 5, "type": "object"}],
  ["pencil", "pencils", {"tone": 5, "type": "object"}],
  ["pendulum", "pendulums", {"tone": 5, "type": "object"}],
  ["penny", "pennies", {"tone": 5, "type": "object"}],
  ["pentagon", "pentagons", {"tone": 5, "type": "object"}],
  ["pepper", "peppers", {"tone": 5, "type": "object"}],
  ["phantom", "phantoms", {"tone": 5, "type": "object"}],
  ["pheasant", "pheasants", {"tone": 5, "type": "object"}],
  ["philosopher", "philosophers", {"tone": 5, "type": "object"}],
  ["phone", "phones", {"tone": 5, "type": "object"}],
  ["phonograph", "phonographs", {"tone": 5, "type": "object"}],
  ["photograph", "photographs", {"tone": 5, "type": "object"}],
  ["physicist", "physicists", {"tone": 5, "type": "object"}],
  ["pianist", "pianists", {"tone": 5, "type": "object"}],
  ["piano", "pianos", {"tone": 5, "type": "object"}],
  ["pickaxe", "pickaxes", {"tone": 5, "type": "object"}],
  ["pickle", "pickles", {"tone": 5, "type": "object"}],
  ["pie", "pies", {"tone": 5, "type": "object"}],
  ["piece of junk", "junk", {"tone": 5, "type": "object"}],
  ["pig", "pigs", {"tone": 5, "type": "object"}],
  ["pigeon", "pigeons", {"tone": 5, "type": "object"}],
  ["pill", "pills", {"tone": 5, "type": "object"}],
  ["pillow", "pillows", {"tone": 5, "type": "object"}],
  ["pineapple", "pineapples", {"tone": 5, "type": "object"}],
  ["pipe", "pipes", {"tone": 5, "type": "object"}],
  ["pirate", "pirates", {"tone": 5, "type": "object"}],
  ["pirhana", "pirhana", {"tone": 5, "type": "object"}],
  ["pistol", "pistols", {"tone": 5, "type": "object"}],
  ["pitchfork", "pitchforks", {"tone": 5, "type": "object"}],
  ["pizza", "pizzas", {"tone": 5, "type": "object"}],
  ["plane", "planes", {"tone": 5, "type": "object"}],
  ["plant", "plants", {"tone": 5, "type": "object"}],
  ["plantain", "plantains", {"tone": 5, "type": "object"}],
  ["plasma creature", "plasma creatures", {"tone": 5, "type": "object"}],
  ["plate", "plates", {"tone": 5, "type": "object"}],
  ["plunger", "plungers", {"tone": 5, "type": "object"}],
  ["poem", "poems", {"tone": 5, "type": "object"}],
  ["police officer", "police officers", {"tone": 5, "type": "object"}],
  ["politician", "politicians", {"tone": 5, "type": "object"}],
  ["polo player", "polo players", {"tone": 5, "type": "object"}],
  ["poodles", "poodles", {"tone": 5, "type": "object"}],
  ["pork chop", "pork chops", {"tone": 5, "type": "object"}],
  ["possum", "possums", {"tone": 5, "type": "object"}],
  ["potato", "potatoes", {"tone": 5, "type": "object"}],
  ["preacher", "preachers", {"tone": 5, "type": "object"}],
  ["predator", "predators", {"tone": 5, "type": "object"}],
  ["priest", "priests", {"tone": 5, "type": "object"}],
  ["prince", "princes", {"tone": 5, "type": "object"}],
  ["princess", "princesses", {"tone": 5, "type": "object"}],
  ["printer", "printers", {"tone": 5, "type": "object"}],
  ["prisoner", "prisoners", {"tone": 5, "type": "object"}],
  ["professor", "professors", {"tone": 5, "type": "object"}],
  ["programmer", "programmers", {"tone": 5, "type": "object"}],
  ["prophet", "prophets", {"tone": 5, "type": "object"}],
  ["proverb", "proverbs", {"tone": 5, "type": "object"}],
  ["psalm", "psalms", {"tone": 5, "type": "object"}],
  ["psychiatrist", "psychiatrists", {"tone": 5, "type": "object"}],
  ["pumpkin", "pumpkins", {"tone": 5, "type": "object"}],
  ["punk", "punks", {"tone": 5, "type": "object"}],
  ["puppet", "puppets", {"tone": 5, "type": "object"}],
  ["puppy", "puppies", {"tone": 5, "type": "object"}],
  ["puzzle", "puzzles", {"tone": 5, "type": "object"}],
  ["pyromaniac", "pyromaniacs", {"tone": 5, "type": "object"}],
  ["python", "pythons", {"tone": 5, "type": "object"}],
  ["quail", "quails", {"tone": 5, "type": "object"}],
  ["quart", "quarters", {"tone": 5, "type": "object"}],
  ["quartz stone", "quartz stones", {"tone": 5, "type": "object"}],
  ["queen", "queens", {"tone": 5, "type": "object"}],
  ["question", "questions", {"tone": 5, "type": "object"}],
  ["quiche", "quiches", {"tone": 5, "type": "object"}],
  ["quill", "quills", {"tone": 5, "type": "object"}],
  ["quilt", "quilts", {"tone": 5, "type": "object"}],
  ["quiver", "quivers", {"tone": 5, "type": "object"}],
  ["quote", "quotes", {"tone": 5, "type": "object"}],
  ["rabbi", "rabbis", {"tone": 5, "type": "object"}],
  ["rabbit", "rabbits", {"tone": 5, "type": "object"}],
  ["radiator", "radiators", {"tone": 5, "type": "object"}],
  ["radio", "radios", {"tone": 5, "type": "object"}],
  ["radish", "radishes", {"tone": 5, "type": "object"}],
  ["rag", "rags", {"tone": 5, "type": "object"}],
  ["raisin", "raisins", {"tone": 5, "type": "object"}],
  ["ram", "rams", {"tone": 5, "type": "object"}],
  ["ramp", "ramps", {"tone": 5, "type": "object"}],
  ["rancher", "ranchers", {"tone": 5, "type": "object"}],
  ["rapier", "rapiers", {"tone": 5, "type": "object"}],
  ["rapper", "rappers", {"tone": 5, "type": "object"}],
  ["rat", "rats", {"tone": 5, "type": "object"}],
  ["rattle", "rattles", {"tone": 5, "type": "object"}],
  ["razor", "razors", {"tone": 5, "type": "object"}],
  ["rebel", "rebels", {"tone": 5, "type": "object"}],
  ["recorder", "recorders", {"tone": 5, "type": "object"}],
  ["recruiter", "recruiters", {"tone": 5, "type": "object"}],
  ["refugee", "refugees", {"tone": 5, "type": "object"}],
  ["reporter", "reporters", {"tone": 5, "type": "object"}],
  ["rhyme", "rhymes", {"tone": 5, "type": "object"}],
  ["rib", "ribs", {"tone": 5, "type": "object"}],
  ["ribbon", "ribbons", {"tone": 5, "type": "object"}],
  ["rifle", "rifles", {"tone": 5, "type": "object"}],
  ["rifleman", "riflemen", {"tone": 5, "type": "object"}],
  ["ring", "rings", {"tone": 5, "type": "object"}],
  ["rival", "rivals", {"tone": 5, "type": "object"}],
  ["roach", "roaches", {"tone": 5, "type": "object"}],
  ["robber", "robbers", {"tone": 5, "type": "object"}],
  ["robe", "robes", {"tone": 5, "type": "object"}],
  ["robin", "robins", {"tone": 5, "type": "object"}],
  ["robot", "robots", {"tone": 5, "type": "object"}],
  ["rogue", "rogues", {"tone": 5, "type": "object"}],
  ["rooster", "roosters", {"tone": 5, "type": "object"}],
  ["roulette", "roulettes", {"tone": 5, "type": "object"}],
  ["ruler", "rulers", {"tone": 5, "type": "object"}],
  ["rumor", "rumors", {"tone": 5, "type": "object"}],
  ["runaway", "runaway", {"tone": 5, "type": "object"}],
  ["runner", "runner", {"tone": 5, "type": "object"}],
  ["runt", "runt", {"tone": 5, "type": "object"}],
  ["rutabaga", "rutabagas", {"tone": 5, "type": "object"}],
  ["saber", "sabers", {"tone": 5, "type": "object"}],
  ["sadist", "sadists", {"tone": 5, "type": "object"}],
  ["sage", "sages", {"tone": 5, "type": "object"}],
  ["sailor", "sailors", {"tone": 5, "type": "object"}],
  ["salad", "salads", {"tone": 5, "type": "object"}],
  ["salamander", "salamanders", {"tone": 5, "type": "object"}],
  ["salmon", "salmon", {"tone": 5, "type": "object"}],
  ["sandwich", "sandwiches", {"tone": 5, "type": "object"}],
  ["saxophone", "saxophones", {"tone": 5, "type": "object"}],
  ["scabbard", "scabbards", {"tone": 5, "type": "object"}],
  ["scapegoat", "scapegoats", {"tone": 5, "type": "object"}],
  ["scar", "scars", {"tone": 5, "type": "object"}],
  ["scarf", "scarves", {"tone": 5, "type": "object"}],
  ["scavenger", "scavengers", {"tone": 5, "type": "object"}],
  ["scholar", "scholars", {"tone": 5, "type": "object"}],
  ["scientist", "scientists", {"tone": 5, "type": "object"}],
  ["scimitar", "scimitars", {"tone": 5, "type": "object"}],
  ["scissors", "scissors", {"tone": 5, "type": "object"}],
  ["scout", "scouts", {"tone": 5, "type": "object"}],
  ["screw", "screws", {"tone": 5, "type": "object"}],
  ["scribe", "scribes", {"tone": 5, "type": "object"}],
  ["seahorse", "seahorses", {"tone": 5, "type": "object"}],
  ["seals", "seals", {"tone": 5, "type": "object"}],
  ["secret", "secrets", {"tone": 5, "type": "object"}],
  ["seed", "seeds", {"tone": 5, "type": "object"}],
  ["senator", "senators", {"tone": 5, "type": "object"}],
  ["sergeant", "sergeants", {"tone": 5, "type": "object"}],
  ["sesame seed", "sesame seeds", {"tone": 5, "type": "object"}],
  ["shadow", "shadows", {"tone": 5, "type": "object"}],
  ["sheep", "sheep", {"tone": 5, "type": "object"}],
  ["shepherd", "shepherds", {"tone": 5, "type": "object"}],
  ["sherrif", "sheriffs", {"tone": 5, "type": "object"}],
  ["shield", "shields", {"tone": 5, "type": "object"}],
  ["ship", "ships", {"tone": 5, "type": "object"}],
  ["shirt", "shirts", {"tone": 5, "type": "object"}],
  ["shoe", "shoes", {"tone": 5, "type": "object"}],
  ["shotgun", "shotguns", {"tone": 5, "type": "object"}],
  ["shovel", "shovels", {"tone": 5, "type": "object"}],
  ["shrimp", "shrimp", {"tone": 5, "type": "object"}],
  ["sidekick", "sidekicks", {"tone": 5, "type": "object"}],
  ["siren", "sirens", {"tone": 5, "type": "object"}],
  ["skeleton", "skeletons", {"tone": 5, "type": "object"}],
  ["skillet", "skillets", {"tone": 5, "type": "object"}],
  ["skirt", "skirts", {"tone": 5, "type": "object"}],
  ["skull", "skull", {"tone": 5, "type": "object"}],
  ["slob", "slobs", {"tone": 5, "type": "object"}],
  ["slogan", "slogans", {"tone": 5, "type": "object"}],
  ["slug", "slugs", {"tone": 5, "type": "object"}],
  ["smile", "smiles", {"tone": 5, "type": "object"}],
  ["snail", "snails", {"tone": 5, "type": "object"}],
  ["snake", "snakes", {"tone": 5, "type": "object"}],
  ["sniper", "snipers", {"tone": 5, "type": "object"}],
  ["snowball", "snowballs", {"tone": 5, "type": "object"}],
  ["snowman", "snowmen", {"tone": 5, "type": "object"}],
  ["sock", "socks", {"tone": 5, "type": "object"}],
  ["soldier", "soldiers", {"tone": 5, "type": "object"}],
  ["song", "songs", {"tone": 5, "type": "object"}],
  ["spaceship", "spaceships", {"tone": 5, "type": "object"}],
  ["speaker", "speakers", {"tone": 5, "type": "object"}],
  ["spectre", "spectres", {"tone": 5, "type": "object"}],
  ["spell", "spells", {"tone": 5, "type": "object"}],
  ["spider", "spiders", {"tone": 5, "type": "object"}],
  ["spirit", "spirits", {"tone": 5, "type": "object"}],
  ["spoon", "spoons", {"tone": 5, "type": "object"}],
  ["spring", "springs", {"tone": 5, "type": "object"}],
  ["spy", "spies", {"tone": 5, "type": "object"}],
  ["square", "squares", {"tone": 5, "type": "object"}],
  ["squid", "squids", {"tone": 5, "type": "object"}],
  ["squire", "squires", {"tone": 5, "type": "object"}],
  ["squirrel", "squirrels", {"tone": 5, "type": "object"}],
  ["stallion", "stallions", {"tone": 5, "type": "object"}],
  ["star", "stars", {"tone": 5, "type": "object"}],
  ["stone", "stones", {"tone": 5, "type": "object"}],
  ["stranger", "strangers", {"tone": 5, "type": "object"}],
  ["stream", "streams", {"tone": 5, "type": "object"}],
  ["student", "students", {"tone": 5, "type": "object"}],
  ["suitcase", "suitcases", {"tone": 5, "type": "object"}],
  ["surgeon", "surgeons", {"tone": 5, "type": "object"}],
  ["survivalist", "survivalists", {"tone": 5, "type": "object"}],
  ["survivor", "survivors", {"tone": 5, "type": "object"}],
  ["swallow", "swallows", {"tone": 5, "type": "object"}],
  ["swan", "swans", {"tone": 5, "type": "object"}],
  ["sweater", "sweaters", {"tone": 5, "type": "object"}],
  ["switchblade", "switchblades", {"tone": 5, "type": "object"}],
  ["sword", "swords", {"tone": 5, "type": "object"}],
  ["syringe", "syringes", {"tone": 5, "type": "object"}],
  ["table", "tables", {"tone": 5, "type": "object"}],
  ["tablet", "tablets", {"tone": 5, "type": "object"}],
  ["taco", "tacos", {"tone": 5, "type": "object"}],
  ["tail", "tails", {"tone": 5, "type": "object"}],
  ["task", "tasks", {"tone": 5, "type": "object"}],
  ["teacher", "teachers", {"tone": 5, "type": "object"}],
  ["teacup", "teacups", {"tone": 5, "type": "object"}],
  ["telephone", "telephones", {"tone": 5, "type": "object"}],
  ["tent", "tents", {"tone": 5, "type": "object"}],
  ["therapist", "therapists", {"tone": 5, "type": "object"}],
  ["thief", "thieves", {"tone": 5, "type": "object"}],
  ["thorn", "thorns", {"tone": 5, "type": "object"}],
  ["thug", "thugs", {"tone": 5, "type": "object"}],
  ["toad", "toads", {"tone": 5, "type": "object"}],
  ["tomato", "tomatoes", {"tone": 5, "type": "object"}],
  ["tooth", "teeth", {"tone": 5, "type": "object"}],
  ["torch", "torches", {"tone": 5, "type": "object"}],
  ["torpedo", "torpedos", {"tone": 5, "type": "object"}],
  ["tortoise", "tortoises", {"tone": 5, "type": "object"}],
  ["tourist", "tourists", {"tone": 5, "type": "object"}],
  ["toy", "toys", {"tone": 5, "type": "object"}],
  ["trader", "traders", {"tone": 5, "type": "object"}],
  ["traitor", "traitors", {"tone": 5, "type": "object"}],
  ["translator", "translators", {"tone": 5, "type": "object"}],
  ["trapezoid", "trapezoids", {"tone": 5, "type": "object"}],
  ["traveller", "travellers", {"tone": 5, "type": "object"}],
  ["treadmill", "treadmills", {"tone": 5, "type": "object"}],
  ["trooper", "troopers", {"tone": 5, "type": "object"}],
  ["trout", "trouts", {"tone": 5, "type": "object"}],
  ["trumpet", "trumpets", {"tone": 5, "type": "object"}],
  ["tuba", "tubas", {"tone": 5, "type": "object"}],
  ["tulip", "tulips", {"tone": 5, "type": "object"}],
  ["turkey", "turkeys", {"tone": 5, "type": "object"}],
  ["turret", "turrets", {"tone": 5, "type": "object"}],
  ["turtle", "turtles", {"tone": 5, "type": "object"}],
  ["typewriter", "typewriters", {"tone": 5, "type": "object"}],
  ["tyrant", "tyrants", {"tone": 5, "type": "object"}],
  ["umbrella", "umbrellas", {"tone": 5, "type": "object"}],
  ["umpire", "umpires", {"tone": 5, "type": "object"}],
  ["unicorn", "unicorns", {"tone": 5, "type": "object"}],
  ["unicycle", "unicycles", {"tone": 5, "type": "object"}],
  ["urn", "urns", {"tone": 5, "type": "object"}],
  ["usher", "ushers", {"tone": 5, "type": "object"}],
  ["vagabond", "vagabonds", {"tone": 5, "type": "object"}],
  ["vase", "vases", {"tone": 5, "type": "object"}],
  ["vegan", "vegans", {"tone": 5, "type": "object"}],
  ["vegetarian", "vegetarians", {"tone": 5, "type": "object"}],
  ["vigilante", "vigilantes", {"tone": 5, "type": "object"}],
  ["viking", "vikings", {"tone": 5, "type": "object"}],
  ["villager", "villagers", {"tone": 5, "type": "object"}],
  ["villain", "villains", {"tone": 5, "type": "object"}],
  ["violin", "violins", {"tone": 5, "type": "object"}],
  ["volleyball", "volleyballs", {"tone": 5, "type": "object"}],
  ["voodoo doll", "voodoo dolls", {"tone": 5, "type": "object"}],
  ["vulture", "vultures", {"tone": 5, "type": "object"}],
  ["wagon", "wagons", {"tone": 5, "type": "object"}],
  ["waiter", "waiters", {"tone": 5, "type": "object"}],
  ["walk", "walks", {"tone": 5, "type": "object"}],
  ["wall", "walls", {"tone": 5, "type": "object"}],
  ["wallet", "wallets", {"tone": 5, "type": "object"}],
  ["wand", "wands", {"tone": 5, "type": "object"}],
  ["wanderer", "wanderers", {"tone": 5, "type": "object"}],
  ["warlock", "warlocks", {"tone": 5, "type": "object"}],
  ["warlord", "warlords", {"tone": 5, "type": "object"}],
  ["warrior", "warriors", {"tone": 5, "type": "object"}],
  ["watch", "watches", {"tone": 5, "type": "object"}],
  ["watchdog", "watchdogs", {"tone": 5, "type": "object"}],
  ["watermelon", "watermelons", {"tone": 5, "type": "object"}],
  ["web", "webs", {"tone": 5, "type": "object"}],
  ["week", "weeks", {"tone": 5, "type": "object"}],
  ["whale", "whales", {"tone": 5, "type": "object"}],
  ["wheel", "wheels", {"tone": 5, "type": "object"}],
  ["whip", "whips", {"tone": 5, "type": "object"}],
  ["wildcat", "wildcats", {"tone": 5, "type": "object"}],
  ["window", "windows", {"tone": 5, "type": "object"}],
  ["wine bottle", "wine bottles", {"tone": 5, "type": "object"}],
  ["wing", "wings", {"tone": 5, "type": "object"}],
  ["wire", "wires", {"tone": 5, "type": "object"}],
  ["wisp", "wisps", {"tone": 5, "type": "object"}],
  ["witch", "witches", {"tone": 5, "type": "object"}],
  ["wizard", "wizards", {"tone": 5, "type": "object"}],
  ["wolf", "wolves", {"tone": 5, "type": "object"}],
  ["woodpecker", "woodpeckers", {"tone": 5, "type": "object"}],
  ["xylophone", "xylophones", {"tone": 5, "type": "object"}],
  ["yak", "yaks", {"tone": 5, "type": "object"}],
  ["yam", "yams", {"tone": 5, "type": "object"}],
  ["yeti", "yetis", {"tone": 5, "type": "object"}],
  ["yo-yo", "yo-yos", {"tone": 5, "type": "object"}],
  ["yoke", "yokes", {"tone": 5, "type": "object"}],
  ["zebra", "zebras", {"tone": 5, "type": "object"}],
  ["zipper", "zippers", {"tone": 5, "type": "object"}],
  ["zombie", "zombies", {"tone": 5, "type": "object"}],
  ["zuchini", "zuchinis", {"tone": 5, "type": "object"}],
]
