module.exports = [
  "the best",
  "the biggest",
  "the brightest",
  "the calmest",
  "the cleanest",
  "the coldest",
  "the cutest",
  "the dumbest",
  "the least interesting",
  "the longest",
  "the loudest",
  "the most amazing",
  "the most anxiety-inducing",
  "the most anxious",
  "the most beautiful",
  "the most brilliant",
  "the most fearsome",
  "the most frustrating",
  "the most infuriating",
  "the most interesting",
  "the most nervous",
  "the most peaceful",
  "the most powerful",
  "the most predictable",
  "the most ridiculous",
  "the most ridiculous",
  "the most unbelievable",
  "the shabbiest",
  "the shiniest",
  "the sleepiest",
  "the smallest",
  "the smartest",
  "the softest",
  "the stupidest",
  "the sweetest",
  "the tallest",
  "the tiniest",
  "the warmest",
  "the weakest",
  "the worst",
];