module.exports = [
  "accelerates the growth of",
  "accepts",
  "acquires",
  "activates",
  "adapts with",
  "adds",
  "adheres to",
  "adjusts",
  "administers medicine to",
  "administrates",
  "admires",
  "advances",
  "advises",
  "advocates against",
  "advocates for",
  "agrees with",
  "aids",
  "alters",
  "amuses",
  "analyses",
  "annoys",
  "anticipates",
  "approaches",
  "argues with",
  "arranges",
  "arrests",
  "asks for forgiveness from",
  "asks for help from",
  "asks impossible favors of",
  "asks stupid questions to",
  "assembles",
  "assists",
  "attacks",
  "attacks",
  "attains",
  "attracts",
  "augments",
  "automates",
  "avoids",
  "balances",
  "bangs",
  "bargains with",
  "battles",
  "begs for forgiveness from",
  "borrows things from",
  "builds",
  "buries things with",
  "buries",
  "buys things from",
  "buys",
  "buys",
  "calculates numbers with",
  "calculates risks with",
  "capitalizes on",
  "captures",
  "carries out nefarious plans with",
  "carries",
  "casts shadows on",
  "catalogues",
  "challenges",
  "chases",
  "chokes",
  "chooses",
  "claims",
  "cleans",
  "clears levels of",
  "collaborates with",
  "collects",
  "collects",
  "combines",
  "communicates with",
  "completes",
  "computes",
  "conceives",
  "conceptualizes",
  "condenses",
  "confuses",
  "consolidates power with",
  "constructs",
  "consumes",
  "controls",
  "converts",
  "coordinates",
  "corrects",
  "counts",
  "creates life with",
  "creates",
  "crushes",
  "cultivates",
  "cuts",
  "damages",
  "deceives",
  "decreases the number of",
  "delights",
  "delivers",
  "delivers",
  "describes",
  "designs",
  "destroys",
  "develops",
  "dies from",
  "directs groups of",
  "discovers secrets about",
  "discovers",
  "dispatches",
  "distributes",
  "documents",
  "downloads",
  "earns",
  "eats",
  "edits",
  "eliminates",
  "employs",
  "encourages",
  "endorses",
  "enforces",
  "engages with",
  "engineers",
  "enlarges",
  "enriches",
  "entertains",
  "establishes bases with",
  "estimates the amount of",
  "examines",
  "expands",
  "explains",
  "explores",
  "facilitates",
  "falls on",
  "familiarizes",
  "fashions",
  "fights",
  "finds",
  "fits together",
  "fixes",
  "flies",
  "focuses on",
  "follows",
  "formalizes",
  "forms groups of",
  "formulates",
  "fortifies",
  "frames",
  "fulfils",
  "furnishes rooms with",
  "gains",
  "gathers",
  "generates",
  "governs cities of",
  "grabs",
  "groups together",
  "guides",
  "handles",
  "harasses",
  "hires",
  "hosts",
  "hunts",
  "hurts",
  "identifies",
  "illuminates",
  "illustrates",
  "implements",
  "improves",
  "improvises",
  "increases the amount of",
  "indoctrinates",
  "influences",
  "innovates",
  "inquires about",
  "inspects",
  "inspects",
  "inspires",
  "installs",
  "instructs",
  "insults",
  "interrogates",
  "interviews",
  "introduces",
  "invents",
  "investigates",
  "invests in",
  "irritates",
  "is chosen by",
  "is damaged by",
  "is deceived by",
  "is delivered to",
  "is destroyed by",
  "is documented by",
  "is earned by",
  "is edited by",
  "is eliminated by",
  "is employed by",
  "is enlarged by",
  "is enriched by",
  "is entertained by",
  "is expanded by",
  "is freed by",
  "is killed by",
  "is lectured by",
  "is measured by",
  "is modified by",
  "is multiplied by",
  "is nailed by",
  "is noticed by",
  "is nuked by",
  "is obeyed by",
  "is operated on by",
  "is processed by",
  "is produced by",
  "is ranked by",
  "is recycled by",
  "is reduced by",
  "is taught Chinese by",
  "is taught English by",
  "is taught manners by",
  "is taught maths by",
  "is taught philosophy by",
  "is taught physical fitness by",
  "is taught psychology by",
  "is taught religions by",
  "is taught science by",
  "is taught street smarts by",
  "is transformed into",
  "isolates",
  "jackknifes",
  "joins",
  "jokes with",
  "judges",
  "juggles",
  "jumps over",
  "jumps over",
  "kicks",
  "kills",
  "kisses",
  "knocks out",
  "laughs about",
  "launches",
  "leads",
  "lectures",
  "levitates",
  "licks",
  "localizes",
  "locates",
  "looks at",
  "loses",
  "maintains",
  "manages",
  "maps",
  "massacres",
  "maximizes",
  "measures",
  "mines",
  "minimizes",
  "models",
  "modernizes",
  "modifies",
  "monitors",
  "motivates",
  "moves",
  "moves",
  "multiplies",
  "nails",
  "negates",
  "notices",
  "nukes",
  "nullifies",
  "obeys",
  "observes",
  "obtains",
  "obtains",
  "offers",
  "opens up",
  "operates on",
  "operates",
  "oppresses",
  "orders",
  "organizes",
  "organizes",
  "orientates",
  "overhauls",
  "owns",
  "participates with",
  "perceives",
  "performs",
  "prepares for",
  "prevents",
  "prioritizes",
  "processes",
  "produces",
  "programs",
  "promotes",
  "proposes to",
  "provides for",
  "publicizes",
  "purchases",
  "questions",
  "quotes",
  "raises",
  "ranks",
  "rates",
  "reacts to",
  "records",
  "recycles",
  "reduces",
  "refines",
  "regulates",
  "rehabilitates",
  "reinforces",
  "rejects",
  "relates with",
  "remodels",
  "reorganizes",
  "repairs",
  "researches",
  "retrieves",
  "reverses",
  "reviews",
  "rewards",
  "runs away from",
  "runs with",
  "salvages",
  "scores",
  "secures",
  "selects",
  "sells",
  "sells",
  "separates",
  "serves",
  "shakes",
  "shanks",
  "shapes",
  "shrinks",
  "simplifies",
  "slaughters",
  "smashes",
  "sneaks up on",
  "solves puzzles made out of",
  "somersaults",
  "spies on",
  "squeezes",
  "stimulates",
  "strategizes with",
  "strengthens",
  "studies",
  "submits",
  "supervises",
  "supplies",
  "supports",
  "surveys",
  "tailors outfits for",
  "targets",
  "teaches Chinese to",
  "teaches English to",
  "teaches manners to",
  "teaches maths to",
  "teaches philosophy to",
  "teaches physical fitness to",
  "teaches psychology to",
  "teaches religions to",
  "teaches science to",
  "teaches street smarts to",
  "terminates",
  "tests",
  "tightens",
  "trades with",
  "trains",
  "transforms",
  "translates",
  "transports",
  "treats",
  "tumbles over",
  "turns",
  "twists",
  "uncovers",
  "unifies",
  "upgrades",
  "uploads",
  "uses",
  "utilizes",
  "validates",
  "values",
  "vandalizes",
  "verifies",
  "views",
  "visits",
  "vomits on",
  "wages war on",
  "walks on",
  "warms up",
  "weighs",
  "welcomes",
  "whispers at",
  "wins",
  "wishes for",
  "wrecks",
  "wrestles",
  "wrestles",
  "writes about",
  "yawns at",
  "yells at",
  "zaps",
  "zooms in on",
];